version: '3.0'
services:
  diarios-fetcher-fetch-all:
    env_file:
      - ./env/docker.env
    image: diarios-fetcher
    volumes:
      - ${DIARIOSDIR}:/home/diarios-fetcher/diarios-oficiais
    command: /bin/diarios-fetcher-exe fetch
    depends_on:
      - postgresql
      - db-history-update
    restart: "no"