version: '3.0'
services:
  diarios-oficiais-backend:
    ports:
      - "80:8080"
      - "443:8083"
    env_file:
      - ./env/simul-prod/docker.env
    image: diarios-oficiais-backend
    depends_on:
      - postgresql
      - pebble
    volumes:
      - ./env/simul-prod/data/certbot/:/home/diarios-backend/certbot/
    restart: unless-stopped
  diarios-fetcher:
    env_file:
      - ./env/simul-prod/docker.env
    image: diarios-fetcher
    volumes:
      - ${DIARIOSDIR}:/home/diarios-fetcher/diarios-oficiais
    restart: always
    depends_on:
      - postgresql
    restart: unless-stopped
  postgresql:
    env_file:
      - ./env/simul-prod/docker.env
    image: postgresql
    volumes:
      - ${PGDATA}:/home/postgres/postgres-datadir
    restart: unless-stopped
  pebble:
    image: letsencrypt/pebble
    command: pebble -config /test/pebble-config.json
    ports:
      - 14000:14000  # ACME port
      - 15000:15000  # Management port
    environment:
      - PEBBLE_VA_NOSLEEP=1
    volumes:
      - ./env/simul-prod/pebble/:/test/
  watchtower:
    image: containrrr/watchtower:0.3.11
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30
    restart: unless-stopped